package com.example.yijia.util.callback;


public enum CallbackType {
    ON_CROP,
    TAG_OPEN_PUSH,
    TAG_STOP_PUSH,
    ON_SCAN,
    FRAGMENT_LETTER_CHOOSEFRIEND_RESULT,
    FRAGMENT_GUARDIANSHIP_CHOOSEFRIEND_RESULT,
    FRAGMENT_AUTHENTICATION_RESULT,
    REFRESHNOTIFY,
    EXIT,
    DOCTOR_GROUP_TITLE_VISIBILITY,
    ROBOT_REMIND_WEEK,
    ROBOT_REMIND_TAG,
    ROBOT_REMIND_ADD
}
